export const MAX_CONTRAPTION_BLOCKS = 16;

export const MOVABLE_BLOCK_TYPES = new Set([
	"createbedrock:hand_crank",
	"createbedrock:shaft",
	"createbedrock:cogwheel",
	"createbedrock:large_cogwheel",
	"createbedrock:gearbox",
	"createbedrock:clutch",
	"createbedrock:encased_chain_drive",
	"createbedrock:water_wheel",
	"createbedrock:millstone",
	"createbedrock:mechanical_press",
	"createbedrock:mechanical_crafter",
	"createbedrock:mechanical_plough",
	"createbedrock:mechanical_roller",
	"createbedrock:mechanical_drill",
	"createbedrock:mechanical_piston",
	"createbedrock:sticky_mechanical_piston",
	"createbedrock:mechanical_piston_head",
	"createbedrock:rope_pulley",
	"createbedrock:hose_pulley",
	"createbedrock:rope",
	"createbedrock:pulley_magnet",
	"createbedrock:gantry_carriage",
	"createbedrock:gantry_shaft",
	"createbedrock:contraption_controls",
	"createbedrock:controls",
	"createbedrock:piston_extension_pole",
	"createbedrock:portable_storage_interface",
	"createbedrock:crushing_wheel",
	"createbedrock:crushing_wheel_controller",
	"createbedrock:andesite_casing",
	"createbedrock:brass_casing",
	"createbedrock:copper_casing",
	"createbedrock:industrial_iron_block",
	"createbedrock:zinc_block",
	"createbedrock:analog_lever",
	"createbedrock:content_observer",
	"createbedrock:display_link",
	"createbedrock:lectern_controller",
	"createbedrock:nixie_tube",
	"createbedrock:powered_latch",
	"createbedrock:powered_toggle_latch",
	"createbedrock:pulse_extender",
	"createbedrock:pulse_repeater",
	"createbedrock:pulse_timer",
	"createbedrock:redstone_contact",
	"createbedrock:redstone_link",
	"createbedrock:redstone_requester",
	"createbedrock:rotation_speed_controller",
	"createbedrock:stock_link",
	"createbedrock:stockpile_switch",
	"createbedrock:speedometer",
	"createbedrock:stressometer",
	"createbedrock:placard",
	"createbedrock:display_board",
	"createbedrock:stock_ticker",
	"createbedrock:cuckoo_clock",
	"createbedrock:mysterious_cuckoo_clock",
	"createbedrock:peculiar_bell",
	"createbedrock:haunted_bell",
	"createbedrock:andesite_door",
	"createbedrock:brass_door",
	"createbedrock:copper_door",
	"createbedrock:framed_glass_door",
	"createbedrock:train_door",
	"createbedrock:steam_whistle",
	"createbedrock:steam_whistle_extension",
	"createbedrock:sail_frame",
	"createbedrock:white_sail",
	"createbedrock:nozzle",
	"createbedrock:linear_chassis",
	"createbedrock:secondary_linear_chassis",
	"createbedrock:radial_chassis",
	"createbedrock:copycat_panel",
	"createbedrock:copycat_step",
	"createbedrock:depot",
	"createbedrock:item_hatch",
	"createbedrock:item_vault",
	"createbedrock:creative_crate",
	"createbedrock:elevator_contact",
	"createbedrock:belt",
	"createbedrock:sail_frame",
	"createbedrock:white_sail"
]);

// These structural blocks carry no block-entity state.  They still receive a
// no-op data adapter so every whitelisted moving type has an explicit
// capture/detach/restore contract.
export const STATELESS_MOVABLE_BLOCK_TYPES = new Set([
	"createbedrock:andesite_casing",
	"createbedrock:brass_casing",
	"createbedrock:copper_casing",
	"createbedrock:industrial_iron_block",
	"createbedrock:zinc_block",
	"createbedrock:steam_whistle_extension",
	"createbedrock:sail_frame",
	"createbedrock:white_sail",
	"createbedrock:linear_chassis",
	"createbedrock:secondary_linear_chassis",
	"createbedrock:radial_chassis",
	"createbedrock:mechanical_drill",
	"createbedrock:mechanical_piston_head",
	"createbedrock:rope",
	"createbedrock:pulley_magnet"
]);

export function isMovableBlockType(typeId) {
	return MOVABLE_BLOCK_TYPES.has(typeId);
}
